server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/stock-db
    username: postgres
    password: password

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

flyway:
  url: jdbc:postgresql://localhost:3306/mysql
  schemas: stock-db
  user: postgres
  password: password